[package]
name = "pavillon-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
pdf = "0.9.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
scraper = "0.19.0"
tempfile = "3.10.1"
